"""Added Question table

Revision ID: 1a662d10d17b
Revises: 0b958aeb6848
Create Date: 2023-05-16 14:52:39.435333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a662d10d17b'
down_revision = '0b958aeb6848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer_a', sa.String(), nullable=True),
    sa.Column('answer_b', sa.String(), nullable=True),
    sa.Column('value_a', sa.Integer(), nullable=True),
    sa.Column('value_b', sa.Integer(), nullable=True),
    sa.Column('value_c', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
