"""Connected tables

Revision ID: ca12bfd1f2fd
Revises: ef9924d3e0f9
Create Date: 2023-05-15 12:19:34.171879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca12bfd1f2fd'
down_revision = 'ef9924d3e0f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
