"""Added repr for Question

Revision ID: 023b61fe1ef5
Revises: 0911cdd8d14d
Create Date: 2023-05-17 10:59:35.846096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023b61fe1ef5'
down_revision = '0911cdd8d14d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
