"""Create Tables

Revision ID: 0911cdd8d14d
Revises: 0f4dd551b278
Create Date: 2023-05-17 09:45:29.476758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0911cdd8d14d'
down_revision = '0f4dd551b278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('housename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer_a', sa.String(), nullable=True),
    sa.Column('answer_b', sa.String(), nullable=True),
    sa.Column('value_a', sa.Integer(), nullable=True),
    sa.Column('value_b', sa.Integer(), nullable=True),
    sa.Column('value_c', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question1', sa.Integer(), nullable=True),
    sa.Column('question2', sa.Integer(), nullable=True),
    sa.Column('question3', sa.Integer(), nullable=True),
    sa.Column('question4', sa.Integer(), nullable=True),
    sa.Column('question5', sa.Integer(), nullable=True),
    sa.Column('question6', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_table('houses')
    # ### end Alembic commands ###
