"""added D option

Revision ID: 09f0b76c76bc
Revises: 0321aec27cea
Create Date: 2023-05-19 10:15:09.420292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f0b76c76bc'
down_revision = '0321aec27cea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('value_d', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'value_d')
    # ### end Alembic commands ###
